import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { switzer } from "@/lib/font";

export const metadata: Metadata = {
  title: "Kedai Inyiak App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${switzer.className} antialiased`}>{children}</body>
    </html>
  );
}
